server:
  port: 8001

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka

spring:

  application:
    name: apigateway-service

  cloud:
    gateway:
      # CORS 설정
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
#            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
        add-to-simple-url-handler-mapping: true
      routes:

        # 로그인 API
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        # 회원가입 API
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/member/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        # 회원 API
        # 로그인과 회원가입을 제외한 회원 서비스로의 API 는 모두 권한 인증 처리
        # TODO: feign api = /members/feign, service api = /member --> 통일 시키키
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # 주문 서비스
        - id: order-payment-service
          uri: lb://ORDER-PAYMENT-SERVICE
          predicates:
            - Path=/order-payment-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-payment-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  secret: member_token